POST http://localhost:8080/api/create-post HTTP/1.1
content-type: application/json

{
    "title": "Post 1",
    "description": "Este es el contenido de mi nuevo postmaosmoas.",
    "content": "La complejidad del caso amplió aún más malsmoasmoasmoasmoas",
    "author_id": 1,
    "categoria": "tech"
}